api:
  address: "0.0.0.0:1337"
  draintimeout: 10
log:
  level: "DEBUG"
tls:
  cert: "./local-dev/certs/local-dev.crt"
  key: "./local-dev/certs/local-dev.key"
uaa:
  enabled: true
  ca: "./local-dev/certs/local-dev-director-ca.crt"
vault: &vault
  address: "http://127.0.0.1:8200"
redirects:
  - type: "upstream"
    rules: []
    vault: *vault
#  - type: "dynamic"
#    rules: []
#    vault: *vault
#  - type: "v1"
#    rules: []
#    vault: *vault

