api:
  address: "0.0.0.0:1337"
  draintimeout: 10
log:
  level: "DEBUG"
vault: &vault
  address: "http://127.0.0.1:8200"
  token: "s.48t1wu9P4mLBgzvA1LOMJ7AV"
  mount: "config-server"
debug:
  disable_auth: true
  disable_tls: true
