# Golang CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11
    working_directory: ~/github.com/zipcar/bosh-vault
    steps:
    - checkout
    - run: make test